# Generated by Django 3.2 on 2021-04-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_loc_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.IntegerField(verbose_name='почтовый индекс')),
                ('region', models.CharField(
                    max_length=34, verbose_name='область/район')),
                ('city', models.CharField(max_length=34,
                 verbose_name='населённый пункт')),
                ('street', models.CharField(max_length=85, verbose_name='улица')),
                ('house', models.CharField(max_length=5, verbose_name='дом')),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': 'адреса',
            },
        ),
    ]
