# Generated by Django 3.2 on 2021-04-19 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_remove_address_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.area'),
        ),
    ]
