# Generated by Django 3.2 on 2021-04-19 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_address_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='code',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.area', verbose_name='регион'),
        ),
    ]
