# Generated by Django 3.2 on 2021-04-19 06:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20210419_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loc',
            name='area',
        ),
        migrations.AddField(
            model_name='loc',
            name='bounds',
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326, verbose_name='границы территории'),
        ),
        migrations.AlterField(
            model_name='loc',
            name='loc',
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name='географический центр'),
        ),
    ]
