# Generated by Django 3.2 on 2021-04-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_loc_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='loc',
            name='okato',
            field=models.CharField(
                blank=True, max_length=34, null=True, verbose_name='ОКАТО'),
        ),
    ]
