# Generated by Django 3.2 on 2021-04-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_loc_okato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='region',
            new_name='area',
        ),
    ]
