# Generated by Django 3.2 on 2021-04-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='title',
            field=models.CharField(
                blank=True, max_length=51, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=17, verbose_name='приложение'),
        ),
        migrations.AlterField(
            model_name='app',
            name='url',
            field=models.CharField(
                blank=True, max_length=17, null=True, verbose_name='стартовая ссылка'),
        ),
    ]
