# Generated by Django 3.2 on 2021-04-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210417_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='url',
        ),
    ]
