# Generated by Django 3.2 on 2021-04-15 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20210415_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(verbose_name='номер')),
            ],
            options={
                'verbose_name': 'кабинет',
                'verbose_name_plural': 'кабинеты',
            },
        ),
        migrations.AlterModelOptions(
            name='dept',
            options={'verbose_name': 'отдел', 'verbose_name_plural': 'отделы'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'профиль',
                     'verbose_name_plural': 'профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True,
                                   verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dept',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.dept', verbose_name='отдел'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_name',
            field=models.CharField(
                blank=True, max_length=34, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='login'),
        ),
        migrations.AddField(
            model_name='dept',
            name='root',
            field=models.ManyToManyField(to='user.Room'),
        ),
    ]
