# Generated by Django 3.2 on 2021-04-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210415_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='этаж'),
        ),
    ]
