# Generated by Django 3.2 on 2021-04-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_room_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(
                blank=True, default=2, verbose_name='этаж'),
        ),
    ]
