# Generated by Django 3.2 on 2021-04-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_room_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='root',
            new_name='room',
        ),
    ]
