# Generated by Django 3.2 on 2021-04-15 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_root_dept_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='room',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.room', verbose_name='комната'),
        ),
    ]
