# Generated by Django 3.2 on 2021-04-19 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51, verbose_name='должность')),
                ('grade', models.CharField(max_length=51,
                 verbose_name='грейд (категория)')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='user.position', verbose_name='должность'),
        ),
    ]
