# Generated by Django 3.2 on 2021-04-19 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_profile_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='user.position', verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='room',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.room', verbose_name='комната'),
        ),
    ]
